sudo: required

language: bash

services:
  - docker

before_install:
  #- docker pull koalaman/shellcheck
  - sudo apt-get install shellcheck

script:
 #- docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/test-shell-scripts
 - ./tests/test-shell-scripts
 #- ./test-dockerfiles
 - ./tests/test-dockerfiles-diff

matrix:
  fast_finish: true
