sudo: required
language: bash
services:
- docker
before_install:
- sudo apt-get install shellcheck
script:
- "./tests/test-shell-scripts"
- "./tests/test-dockerfiles-diff"
matrix:
  fast_finish: true
notifications:
  slack:
    rooms:
      - secure: "x+DhlS8Ghe9u6kEX7ABxzYLWm6Xlsv6f6RF7EjbCClX1Ln3Xjac5hhwFvMszlUpa+XbplMhz7dMvYzj/0nQtSe5qylvHor1JLnwbgkh0tuvvQAFva73oK+x/xopaJjC+wFadvXjih9rMRMz7PbeA5GzZLiceAnzz29TnqYYR7fEm44c88MNGhrsr9uBzufYTSt8NEblb3eIaVLRqHUeemVxIn6n3SGkDOb7mhyAv0Je0a+eVLlZ2KAx2I7QjPrAM9LFkBaLfO0rZ6DCBRZV80bW4zVbAkJ2zFmcpFmUf4lzBoZpCesmOmDAQ7m1azF98MCkUXeJwBk2fEe6DD+I0OVphZiXPLo3jFolKAMuko95lV57G76WcbVxvK9xRo4F5dd9CKC611DlqpZrIy+c06+HSFld0pCeEvgqeSVUrCyHT38o+SHSAu6SaQSqKZuEUMWR3e6D3/sgqUM3ZMqa9rrrq0xR7l9N1KmxMQRQQ+bMSJxwiIPZ2FajZHMJsLQe8gWRZQAA7JDiXuOcjhABBHHup4Iewwtk/muafiOJgdgT5pLMDzr34JVIjgtjlXRXGSWXYmtiJSiTegfKGbmyB2ILsXGVwNAWrfcODuPBu4oCJlY2YhORCTZVt0UnKOBWuksyNqxV6yDMaaOyi6GnQ7j2WHtANyhq+N2ZmWDQyvvk="
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always
    template:
      - "Repository: %{repository} Branch : %{branch}"
      - "Commit: <%{compare_url}|%{commit}> - %{commit_message}"
      - "Author: %{author}"
      - "Build: <%{build_url}|%{build_number}> has %{result}"
      - "Duration: %{duration}"
      - "PR <%{pull_request_url}|#%{pull_request_number}"

  webhooks:
    urls:
      - secure: tgn6vAsKkqaHp0omfqTIOGG2A7HXje2nYC9okLDW8NvmTSVWq+2B2wimSekq8dNRGT5MCqsZaMtzIBDYYOJydxKj7kh4qJnQjV6kgoB+s+8U/SC6I5BNnQNa5dWbIWPAdob3tIegp+OhtKoGiQeQTTZZb9Z7anCjOx+D3G4SWbu+NsdOpXbNRIfldYnW17ml3yIvAdtcvCYqkQNiU7oJ1dr85DcIOhBuEl1lTbhbMv1VdIQrWs4Mh7rfLBYs2w8vUnai4M6fY/sTbIuDWw5dAKIMvtS6VpzGpglJD4Bbu+MA4+ZIdCFbEU0WExtDWVNdFD1JorqLIiTFrYpLuKtTI2UX9IqM3SSKhAL53kacpoWsKcD+RpJL2oCb4QaL8bXWZtZBJ7STMqhIWFNsb91K9euLu0wiETHdYBhIRGr25jqiGYMq3w7XFIfAEuYnTaD1EZAiyHyVOLcWls+R/dILBP2tdV7zT6VZ7tEmgBFJrXGEYE3QCzfMp/vmWZxKPLVeCfGVvNacGseNYHv7NisT7ro3efY55/ia+Gp5sDcQWLL6zoDON8EF6nGkBIhVWiV2FE2zwlvTYlvuKXGE6LUIoZV7K1yt06i2/E1wXzISvmmH//VetHdeXTstwJVMZ15i5xpOHCW99NDDBR7vqjc2e/XaDWpSrmghIc5m9tXuOY0=
      - secure: TsXjG2H6VdzChUPoDHnzqxakZ5+QklaeGbguyxIe/JFbu5cJjdxoOt2n0zMCYKEzgvyYtu5wDhgtUv7gMv+AfMngiZHOX9BJHZsQXGV0w37nyVSai3mm7vfKODWLJK3pvU9xTFWaNQVjbEo99311wCsEl1+495AT6oV8dWI/VEZcbXyLKon699QtXLT319IJnEjAIB2yOfqZxWmgaZ2fevBL0brfKm6DHn7GTkgaJJrQb2nCEbcymRNyZlDisP1rQ+2lLwnn33EKkzlFM+eC9IsCNceaqm7l4tgqfqUrnZSFJeY8WWnPy6m7/ui4tza+MZoX6vGbAu3wqsUMFdlkLpj8ekHwO937h7z9HM64Z8kRXLxcWAyvVSVuYTPCGzsfRryWc3vU6SGHJK4Pkg/MAMz20MXfvbwroM2ZuPTughuW35A3GL7jWc3KBk05xxejQzFZFmXR/3y4YT+fwT/T0COcFr8/YsNDVENL/B2dyzcuyuRQgSioypCRJAP5Xf0ZYuHgbkWTFEYxYxo3nIWm4MF+fxzXbt3hqgZVQI7R3kP/ihx2zIUckIn98icPxffW8MW8sjpQTQJSh1l5mJObaWe/klJC8vqv50MP9HF26X/i4egBKqeteVMLReS8CzmbRkWU5o4eOx2720aPz3p+2+JkPLoz/4UibLpLwUKcEBE=
      - secure: ZaPKzN/2GWLQ+5j0tya09aiuk/IIaWN8e5lyukVg9Vp05sI6JIP6qJLQvP31tduVLNIukvCctu2FyJESrobu7i0qrUcTJJ2LIByLOKGaqZpfidMT1Fx6t4F3mjgbQ5z4LcHbkhtERqV9jpMOrXho6MK5+mM4bYs0cP7uIaVwZ4YVMIUBNnd69alv3AXLf4IwIIWOVZPukBwlMYl4keUXJzLril6vweYlUm+ZZnxMDzoMil66prI9sUB3KZhn6OhPxvIujnm/5WQ9F7nyIFYHHGaoYPoKqc6zxXnrcMW+1NRC6mWqK1Q4nXnn7dZ1V7fxv7SHo2WnDeUxYqufmbI5BzxOJ6H04WZemCtj3Z18Qo55gW2NWXTG12aTnxFWAADkPIxUciJyW6QLG+27ZgClP19PBco4o7i/nGWlqyiy215iZJRPoBV7OkYvDVRmOTU5Zdkz3Y3PE19Wtlwfc8B2DZqC09OjXuOvkGssbTTWZTCrXeOO5STmU4NO6Lo/V8Srb1FYP8C1dMlF3PL18ZK02w9t9803KDle2sFDGAMf2hhS0qCWfjA0KsdY1dWjMvx84DkNLH/El338h+e2PIvTjYQofXBwuluDGQehnNUt0jnISmhfZuTkfEyPZj+6IV07VQhHlEidalAk3gt8QSa66xzCDPFP+QgQ5B8pE6SfFCg=
    on_success: always # default: always
    on_failure: never # default: always
    on_start: never   # default: never
