#!/usr/bin/env bash

# This is a bash script to launch gnome-builder using docker helper core
# Version:1.2
# Author: Prasad Tengse
# Licence: MIT
# Github Repository: https://github.com/tprasadtp/minchu
# Requirements - Bash v4.4 and above
#              - docker installed and you can run without sudo.
#              - docker-helper-core to be present in current directory
#              - Change the volumes to be mounted appropriately.
#              - docker-ce v17 and a above [lower versions might work but not tested.]
#              - Tested on 17.04 zesty 64 bit Ubuntu GNOME
#              - Kitematic is  recomended

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Changelogs~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# v1.0      - Split core-functions into a seperate module
# v1.1      - Ability to stop, delete containers
# v1.2      - Added checks to make sure that the script will work when
#             dockerfiles are in ~/.local/bin.


SCRIPT=$(basename "$0")

#defining curret directory
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

#Define variables required by docker-helper-core
container_name="gnome_builder" #name of the container to be run.
# Use _ in container names. use - in images and directories
docker_folder="gnome-builder" #Folder in which Dockerfile is present
docker_image="gnome-builder" #Name of the docker image
image_tag="latest" #tag of the docker image
HELPER_VERSION="1.2 βeta"

#----- Import docker-helper-core -----#
if [ -e docker-helper-core ]; then
    #shellcheck source=./dockerfiles/docker-helper-core
    . $dir/docker-helper-core
elif command -v docker-helper-core >&/dev/null; then
  #shellcheck source=./dockerfiles/docker-helper-core
  source docker-helper-core
else
  printf "Cannot find docker-helper-core in current directory or PATH.\nHelper script cannot continue!!\n"
  exit 1;
fi

#------------------------------------#

function  dockerx_gnome-builder()
{
  # Wrapper for docker command to launch gnome builder
  # Input: none
  # Output: Runs app in docker
  # Expects: Docker to be installed and can run it wothout sudo

  docker run -d \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e DISPLAY=unix$DISPLAY \
  --device /dev/snd \
  --name ${container_name} \
  gnome-builder:latest

}

# Call main function in docker-helper-core to process arguments.
main "$@"
