#!/usr/bin/env bash

# This is a bash script to launch jekyll using docker helper core
# Version: 1.0
# Author: Prasad Tengse
# Licence: MIT
# Github Repository: https://github.com/tprasadtp/minchu
# Requirements - Bash v4.4 and above
#              - docker installed and you can run without sudo.
#              - docker-helper-core to be present in current directory
#              - Change the volumes to be mounted appropriately.
#              - docker-ce v17 and a above [lower versions might work but not tested.]
#              - Tested on 17.04 zesty 64 bit Ubuntu GNOME
#              - Kitematic is  recomended

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Changelogs~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# v1.0      - Initial writeup


SCRIPT=$(basename "$0")

#defining curret directory
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
# Other variables required
readonly JEKYLL_VERSION=3.5
readonly flag_local_dockerfile=false
#Define variables required by docker-helper-core
container_name="jekyll" #name of the container to be run.
# Use _ in container names. use - in images and directories
# docker_folder="jekyll" #Folder in which Dockerfile is present
# docker_image="jekyll" #Name of the docker image
image_tag=${JEKYLL_VERSION} #tag of the docker image
HELPER_VERSION="1.0 βeta"
repo=jekyll/builder #repository name from which to pull the image

#----- Import docker-helper-core -----#
if [ -e docker-helper-core ]; then
    #shellcheck source=./dockerfiles/docker-helper-core
    . "$dir"/docker-helper-core
elif command -v docker-helper-core >&/dev/null; then
  #shellcheck source=./dockerfiles/docker-helper-core
  source docker-helper-core
else
  printf "Cannot find docker-helper-core in current directory or PATH.\nHelper script cannot continue!!\n"
  exit 1;
fi

#------------------------------------#

function  dockerx_jekyll()
{
  # Wrapper for docker command to launch jekyll
  # Builds the site watches for changes and regenerates automatically.
  # Input: none
  # Output: Runs app in docker
  # Expects: Docker to be installed and can run it wothout sudo
  docker run --rm \
    --volume="$PWD":/srv/jekyll \
    -d jekyll/builder:"$JEKYLL_VERSION" \
    jekyll build && jekyll serve

}

# Call main function in docker-helper-core to process arguments.
main "$@"
